Add golden tests for templates.
wavesplatform/nodemon pull request #150
Opened 2023-01-27 15:39 UTC by nickeskov

2023-02-01 06:04 UTC, esuwu approved these changes

2023-02-01 07:29 UTC, alexeykiselev requested changes
I see a mixed style of using spaces in templates. I think we have to choose one put or not put spaces before and after double curly braces.

2023-02-01 07:29 UTC, alexeykiselev commented on cmd/bots/internal/common/templates/alerts/base_target_alert.html
> +Node: <code>{{ .Node}}</code>
Looks like one space is missed before closing double curly braces `}}`. And below.

2023-02-01 07:29 UTC, alexeykiselev commented on cmd/bots/internal/common/templates/alerts/base_target_alert.html
> +Node: <code>{{ .Node}}</code>
I know that it's just formatting.

2023-02-13 07:47 UTC, alexeykiselev approved these changes

2023-02-13 07:47 UTC, merged