Removed path.Join function
wavesplatform/nodemon pull request #62
Opened 2022-08-04 03:45 UTC by esuwu

For some reason, path.Join function adds an extra "/" after "http" which makes it fail to request a version

2022-08-05 10:08 UTC, nickeskov requested changes

2022-08-06 16:01 UTC, esuwu commented on pkg/scraping/client.go
> +	baseUrl.Path = filepath.Join(baseUrl.Path, addUrl.Path)
![Screenshot from 2022-08-06 19-00-47](https://user-images.githubusercontent.com/41806871/183256675-93a08c0c-8650-4cb5-aedc-a7243f69d652.png)

2022-08-06 16:05 UTC, nickeskov commented on pkg/scraping/client.go
> +	baseUrl.Path = filepath.Join(baseUrl.Path, addUrl.Path)
It's ok, just dismiss it.

2022-08-08 12:56 UTC, nickeskov approved these changes

2022-08-08 13:00 UTC, merged