Removed http and https prefixes
wavesplatform/nodemon pull request #85
Opened 2022-09-21 05:21 UTC by esuwu

2022-09-21 12:19 UTC, nickeskov requested changes

2022-09-21 12:19 UTC, nickeskov commented on cmd/tg_bot/internal/environment.go
> +	}
You're changing a copy of element in the `NodesStatus` slice. Use `for i: range nodesStatusResp.NodesStatus` cycle to mutate `NodesStatus` slice elements.

2022-09-21 12:19 UTC, nickeskov commented on cmd/tg_bot/internal/environment.go
> +		node.Url = strings.ReplaceAll(node.Url, entities.HttpsScheme+"://", "")
I thing https should be first.

2022-09-27 06:53 UTC, esuwu commented
https://github.com/wavesplatform/nodemon/pull/87
The comments have been taken into account

2022-09-27 06:53 UTC, closed without merging