Improved logs
wavesplatform/nodemon pull request #90
Opened 2022-09-30 04:34 UTC by esuwu

2022-09-30 05:56 UTC, esuwu commented
https://github.com/wavesplatform/nodemon/issues/71

2022-09-30 09:20 UTC, nickeskov commented on pkg/api/api.go
> +	a.zap.Info(fmt.Sprintf("Statement for node %s has been put into the storage, height %d, statehash %s\n", escapedNodeName, statement.Height, sumhash))
Please, fix this issue.
```go
nodeName := r.Header.Get("node-name")
escapedNodeName := strings.Replace(nodeName, "\n", "", -1)
escapedNodeName = strings.Replace(escapedNodeName, "\r", "", -1)
```

2022-09-30 18:10 UTC, nickeskov commented on pkg/api/api.go
> +	a.zap.Info(fmt.Sprintf("Statement for node %s has been put into the storage, height %d, statehash %s\n", escapedNodeName, statement.Height, sumhash))
Issue has been fixed, my bad.

2022-10-14 16:08 UTC, nickeskov requested changes
@esuwu Please, use zap in all places instead of standard logger.

```shell
$ grep -rn "log\." pkg cmd | grep -v "test.go"
pkg/storing/nodes/nodes.go:93:          log.Printf("New node #%d at '%s' was stored", id, url)
pkg/storing/nodes/nodes.go:111:         log.Printf("New node #%d at '%s' was stored", id, url)
pkg/storing/nodes/nodes.go:131:                 log.Printf("Node #%d at '%s' was deleted", id, url)
cmd/bots/discord/discord.go:28:                 log.Println(err)
cmd/bots/discord/discord.go:37:         log.Fatalf("can't initialize zap logger: %v", err)
cmd/bots/discord/discord.go:42:                 log.Println(err)
cmd/bots/internal/common/init/init.go:30:       log.Printf("telegram chat id for sending alerts is %d", chatID)
cmd/bots/internal/common/init/init.go:45:       log.Printf("discord chat id for sending alerts is %s", chatID)
cmd/bots/telegram/telegram.go:28:                       log.Println(err)
cmd/bots/telegram/telegram.go:37:               log.Fatalf("can't initialize zap logger: %v", err)
cmd/bots/telegram/telegram.go:42:                       log.Println(err)
cmd/nodemon/nodemon.go:44:                      log.Println(err)
cmd/nodemon/nodemon.go:53:              log.Fatalf("can't initialize zap logger: %v", err)
cmd/nodemon/nodemon.go:58:                      log.Println(err)
```

2022-10-18 21:09 UTC, nickeskov approved these changes

2022-10-18 21:13 UTC, merged